spring:
  application:
    name: eureka-server1
server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/