server:
  port: 8002
  servlet:
    context-path: /client2

spring:
  application:
    name: service-consumer
management:
  endpoints:
    web:
      exposure:
        include: health, info, hystrix.stream
